#!/bin/bash

# 🚀 HFRP Relief - Domain Setup Script for familyreliefproject.org
# This script helps configure your environment for the new domain

echo "🌐 Setting up familyreliefproject.org domain configuration..."

# Create production environment template
cat > .env.production.template << EOF
# ==============================================
# PRODUCTION ENVIRONMENT VARIABLES
# ==============================================
# Copy these to your hosting platform (Vercel, Netlify, etc.)

# Production Settings
NODE_ENV=production
NEXT_PUBLIC_SITE_URL=https://www.familyreliefproject.org
NEXT_PUBLIC_DONATION_TEST_MODE=false

# ==============================================
# DONORBOX CONFIGURATION
# ==============================================
# Replace with your actual Donorbox campaign IDs
NEXT_PUBLIC_DONORBOX_MAIN_CAMPAIGN=your-main-campaign-id-here
NEXT_PUBLIC_DONORBOX_MEMBERSHIP_CAMPAIGN=your-membership-campaign-id-here
NEXT_PUBLIC_DONORBOX_DAILY_GIVING_CAMPAIGN=your-daily-campaign-id-here

# ==============================================
# EMAIL CONFIGURATION
# ==============================================
# Resend (Recommended)
EMAIL_SERVICE=resend
RESEND_API_KEY=re_your_resend_api_key_here
RESEND_FROM_EMAIL=noreply@familyreliefproject.org
RESEND_TO_EMAIL=contact@familyreliefproject.org

# Alternative: SendGrid
# EMAIL_SERVICE=sendgrid
# SENDGRID_API_KEY=SG.your_sendgrid_api_key_here
# SENDGRID_FROM_EMAIL=noreply@familyreliefproject.org
# SENDGRID_TO_EMAIL=contact@familyreliefproject.org

# ==============================================
# ANALYTICS & TRACKING
# ==============================================
# Google Analytics 4 (Optional)
NEXT_PUBLIC_GA_MEASUREMENT_ID=G-XXXXXXXXXX

# ==============================================
# SECURITY
# ==============================================
# Generate a secure random string for production
NEXTAUTH_SECRET=your-secure-32-character-random-string-here

# ==============================================
# STRIPE (if using direct Stripe integration)
# ==============================================
# Only needed if you're using Stripe directly instead of Donorbox
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_xxx_REDACTED_xxxyour_stripe_key
# STRIPE_SECRET_KEY=sk_live_xxx_REDACTED_xxxyour_stripe_secret_key

EOF

# Update vercel.json with production settings
cat > vercel.json << EOF
{
  "version": 2,
  "routes": [
    {
      "src": "/admin/(.*)",
      "dest": "/admin/\$1"
    },
    {
      "src": "/(.*)",
      "dest": "/\$1"
    }
  ],
  "env": {
    "NODE_ENV": "production"
  },
  "functions": {
    "app/api/**/*.js": {
      "maxDuration": 10
    }
  },
  "headers": [
    {
      "source": "/(.*)",
      "headers": [
        {
          "key": "X-Content-Type-Options",
          "value": "nosniff"
        },
        {
          "key": "X-Frame-Options",
          "value": "DENY"
        },
        {
          "key": "X-XSS-Protection",
          "value": "1; mode=block"
        },
        {
          "key": "Referrer-Policy",
          "value": "origin-when-cross-origin"
        }
      ]
    }
  ]
}
EOF

# Create deployment checklist
cat > DEPLOYMENT_CHECKLIST_familyreliefproject.md << EOF
# 🚀 Deployment Checklist - familyreliefproject.org

## Pre-Deployment Setup

### 1. Domain & DNS Configuration
- [ ] **Domain purchased**: familyreliefproject.org
- [ ] **DNS records added** (see DOMAIN_CONNECTION_GUIDE.md)
- [ ] **SSL certificate** will be auto-generated by hosting platform

### 2. Email Service Setup
- [ ] **Resend account** created at resend.com
- [ ] **Domain verified** in Resend dashboard
- [ ] **API key** generated and saved securely
- [ ] **DNS records** added for email authentication

### 3. Donorbox Configuration
- [ ] **Real campaign IDs** obtained from Donorbox dashboard
- [ ] **Test donations** completed successfully
- [ ] **Thank you pages** configured
- [ ] **Email confirmations** enabled

### 4. Hosting Platform Setup

#### If Using Vercel:
- [ ] **GitHub repository** connected to Vercel
- [ ] **Environment variables** added in Vercel dashboard
- [ ] **Custom domain** added in Vercel settings
- [ ] **SSL certificate** auto-generated

#### If Using Netlify:
- [ ] **GitHub repository** connected to Netlify
- [ ] **Environment variables** added in Netlify dashboard
- [ ] **Custom domain** configured in site settings
- [ ] **SSL certificate** auto-generated

## Deployment Steps

### 1. Environment Variables
Copy all variables from \`.env.production.template\` to your hosting platform:

**Critical Variables:**
- \`NEXT_PUBLIC_SITE_URL=https://www.familyreliefproject.org\`
- \`NEXT_PUBLIC_DONATION_TEST_MODE=false\`
- \`RESEND_API_KEY=re_your_actual_key\`
- \`RESEND_FROM_EMAIL=noreply@familyreliefproject.org\`

### 2. Deploy & Test
- [ ] **Initial deployment** successful
- [ ] **Custom domain** connected and SSL active
- [ ] **All pages load** correctly
- [ ] **Donation flow** tested with small real donation (\$1-5)
- [ ] **Contact form** sends emails successfully
- [ ] **Admin panel** accessible with credentials

### 3. Go-Live Tasks
- [ ] **Test mode disabled**: \`NEXT_PUBLIC_DONATION_TEST_MODE=false\`
- [ ] **Real donation test**: Make small donation to verify flow
- [ ] **Email functionality**: Test contact form submission
- [ ] **Mobile testing**: Verify responsive design works
- [ ] **Social media**: Update links to new domain

## Post-Launch Monitoring

### Week 1:
- [ ] **Monitor donations**: Ensure Donorbox integration working
- [ ] **Check analytics**: If Google Analytics configured
- [ ] **Test forms**: Contact form and newsletter signup
- [ ] **Mobile performance**: Test on real devices

### Week 2:
- [ ] **Email deliverability**: Monitor spam rates
- [ ] **Site speed**: Check Core Web Vitals scores
- [ ] **Error monitoring**: Review hosting platform logs
- [ ] **Backup verification**: Ensure code is backed up

## Emergency Contacts

### Technical Support:
- **Domain Registrar**: [Your registrar support]
- **Hosting Platform**: Vercel/Netlify support
- **Email Service**: Resend support (support@resend.com)

### Quick Fixes:
- **Site down**: Check hosting status page first
- **Donations not working**: Verify Donorbox campaign IDs
- **Emails not sending**: Check Resend dashboard for errors
- **SSL issues**: Usually auto-resolve within 24 hours

---

**🎉 Success!** Once all items are checked, familyreliefproject.org will be fully operational!
EOF

echo "✅ Configuration files created:"
echo "   - .env.production.template (environment variables)"
echo "   - vercel.json (updated with security headers)"
echo "   - DEPLOYMENT_CHECKLIST_familyreliefproject.md (step-by-step guide)"
echo ""
echo "🔧 Next steps:"
echo "1. Review DOMAIN_CONNECTION_GUIDE.md for detailed setup"
echo "2. Use .env.production.template to configure your hosting platform"
echo "3. Follow DEPLOYMENT_CHECKLIST_familyreliefproject.md for deployment"
echo ""
echo "🌐 Your site will be live at: https://www.familyreliefproject.org"
